export {default as Home} from './Home'
export {default as Contact} from './Contact'
export {default as Cart} from './Cart'
export {default as Admin} from './Admin'
export {default as OrderHistory} from './OrderHistory'